### ISSUE TITLE
README.md needs to address required dependencies not mentioned

### ISSUE THREAD

**Issue by texadactyl** [lukekulik/solar-system#2]
```
python3 main.py     # or python main.py

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from vis import rate, vector  # importing vPython module
ModuleNotFoundError: No module named 'vis'
```
README.md dependencies are already installed.
Running on Xubuntu Linux 18.04.1 LTS, up-to-date.
Python 2.7.15rc1 and 3.6.7 and related package libraries are up-to-date.  
Fails on both Python 2 and 3 as depicted earlier.

**Comment by darius-luca-tech** [comment]
I have the same problem +))

**Comment by Bladestorm25** [comment]
I got vis to work - had to install vpython and change to vpython.
Now it has typerror: Vector needs 3 components from self.ambient (value)
?? Any thoughts? I think its from the vis package but I dont have that in this code? Im very new to this

**Comment by texadactyl** [comment]
Closed due to lack of interest.

**Comment by Antricks** [comment]
vis is the package name used for vpython in VPython 6 (Only supported by Python 2.x). Also the class materials is typical for VPython 6 as in VPython 7 it's named textures.
Simply renaming vis to vpython is not sufficient because of this and other problems occuring in the code (typerror: Vector needs 3 components from ...).
Unfortunately it seems to be pretty hard to set up VPython 6 in Linux. With enough efford of course it would be possible to modify the code to run on VPython 7.

**Comment by texadactyl** [comment]
@Antricks - appreciate your write-up.

Perhaps, someday, some energetic student will download this project ZIP and restart it with (a) Python 3 [or some other *supported* scientific-oriented language like Julia] and (b) support it.
